name: Build and Publish

on:
  release:
    types: [published]

permissions:
  contents: write  # required for uploading release assets

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Ensure the latest artifact actions are used
      - name: Ensure latest artifact actions
        uses: actions/upload-artifact@v4

      - name: Ensure latest download
        uses: actions/download-artifact@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Build the package
        run: poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --no-interaction

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
