name: Build and Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
    
    - name: Install dependencies
      run: poetry install --no-interaction --no-root
    
    - name: Build the package
      run: poetry build
    
    - name: Install GitHub CLI
      run: sudo apt-get install -y gh
    
    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
    
    - name: Upload release assets
      run: |
        for file in dist/*; do
          gh release upload "${{ github.event.release.tag_name }}" "$file"
        done